spring.application.name=product-service
server.port=8081

spring.data.mongodb.uri=mongodb://mongodb:27017/product-service

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka

management.endpoints.web.exposure.include=health,prometheus
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
